# Generated by Django 5.2.17 on 2026-09-16 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0001_initial"),
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("school_code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=200)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "distance_to_iif_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "gender_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("boys", "Boys"),
                            ("girls", "Girls"),
                            ("co-ed", "Co-ed"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "school_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("government", "Government"),
                            ("private", "Private"),
                            ("aided", "Aided"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "medium",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("telugu", "Telugu"),
                            ("english", "English"),
                            ("urdu", "Urdu"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "grades_offered",
                    models.CharField(
                        blank=True, help_text="e.g. '6,7,8'", max_length=50
                    ),
                ),
                ("total_sections", models.PositiveIntegerField(blank=True, null=True)),
                ("principal_name", models.CharField(blank=True, max_length=150)),
                ("principal_phone", models.CharField(blank=True, max_length=20)),
                ("principal_email", models.EmailField(blank=True, max_length=254)),
                ("principal_acknowledged", models.BooleanField(default=False)),
                ("lab_room", models.BooleanField(blank=True, null=True)),
                ("internet", models.BooleanField(blank=True, null=True)),
                ("smart_board", models.BooleanField(blank=True, null=True)),
                ("kit_storage", models.BooleanField(blank=True, null=True)),
                ("maps_link", models.URLField(blank=True)),
                ("iif_poc", models.CharField(blank=True, max_length=150)),
                ("observations", models.TextField(blank=True)),
                ("next_steps", models.TextField(blank=True)),
                ("visited_by", models.CharField(blank=True, max_length=150)),
                ("visit_date", models.DateField(blank=True, null=True)),
                (
                    "external_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Original Google Form Submission ID.",
                        max_length=64,
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schools",
                        to="programs.programinstance",
                    ),
                ),
                (
                    "school_photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="files.file",
                    ),
                ),
            ],
            options={
                "ordering": ["school_code"],
            },
        ),
        migrations.CreateModel(
            name="SchoolGradeEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("grade", models.PositiveSmallIntegerField()),
                ("total_sections", models.PositiveIntegerField(default=0)),
                ("total_students", models.PositiveIntegerField(default=0)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_enrollments",
                        to="schools.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchoolTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "grades_taught",
                    models.CharField(blank=True, help_text="e.g. '6,7'", max_length=50),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teachers",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SessionSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("grade", models.PositiveSmallIntegerField()),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("mon", "Monday"),
                            ("tue", "Tuesday"),
                            ("wed", "Wednesday"),
                            ("thu", "Thursday"),
                            ("fri", "Friday"),
                            ("sat", "Saturday"),
                        ],
                        max_length=3,
                    ),
                ),
                ("time", models.TimeField()),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_schedules",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="school",
            constraint=models.UniqueConstraint(
                fields=("instance", "school_code"),
                name="unique_school_code_per_instance",
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolgradeenrollment",
            constraint=models.UniqueConstraint(
                fields=("school", "grade"), name="unique_grade_enrollment_per_school"
            ),
        ),
    ]
