# Generated by Django 5.2.17 on 2026-09-16 11:32

import apps.files.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to=apps.files.models.upload_path)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("size", models.PositiveIntegerField(default=0)),
                ("entity_type", models.CharField(max_length=100)),
                ("entity_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "legacy_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Original Google Drive URL, kept as a fallback until fully migrated.",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="files_file_entity__d85b4c_idx",
                    )
                ],
            },
        ),
    ]
