# Generated by Django 5.2.17 on 2026-09-16 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0001_initial"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KitDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("delivered_by", models.CharField(blank=True, max_length=150)),
                ("received_by", models.CharField(blank=True, max_length=150)),
                ("date_of_delivery", models.DateField()),
                ("grade_6_kit", models.BooleanField(default=False)),
                ("grade_7_kit", models.BooleanField(default=False)),
                ("grade_8_kit", models.BooleanField(default=False)),
                ("grade_9_kit", models.BooleanField(default=False)),
                (
                    "external_ref",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "acknowledgement_letter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="files.file",
                    ),
                ),
                (
                    "delivery_proof_photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="files.file",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kit_deliveries",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_of_delivery"],
            },
        ),
    ]
