# Generated by Django 5.2.17 on 2026-09-16 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SLSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("grade", models.PositiveSmallIntegerField()),
                ("section", models.CharField(max_length=5)),
                ("teacher", models.CharField(blank=True, max_length=150)),
                ("sl_name", models.CharField(max_length=150)),
                ("interested_in_role", models.BooleanField(default=False)),
                ("attendance_above_90", models.BooleanField(default=False)),
                (
                    "sl_status",
                    models.CharField(
                        choices=[
                            ("selected", "Selected"),
                            ("not_selected", "Not Selected"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("speaks_clearly", models.BooleanField(default=False)),
                ("speaks_loudly", models.BooleanField(default=False)),
                ("understands_english", models.BooleanField(default=False)),
                ("teacher_acknowledged", models.BooleanField(default=False)),
                (
                    "external_ref",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sl_selections",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["school", "grade", "section"],
            },
        ),
    ]
