# Generated by Django 5.2.17 on 2026-09-16 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0001_initial"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentHeadcount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("grade", models.PositiveSmallIntegerField()),
                ("section", models.CharField(max_length=5)),
                ("total_sl", models.PositiveIntegerField(default=0)),
                ("total_clusters", models.PositiveIntegerField(default=0)),
                ("total_teams", models.PositiveIntegerField(default=0)),
                ("total_students", models.PositiveIntegerField(default=0)),
                (
                    "extraction_status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("extraction_error", "Extraction Error"),
                            ("needs_validation", "Needs Validation"),
                        ],
                        default="ok",
                        max_length=20,
                    ),
                ),
                (
                    "count_validation",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("mismatch", "Counts Mismatch"),
                            ("needs_validation", "Needs Validation"),
                        ],
                        default="ok",
                        max_length=20,
                    ),
                ),
                (
                    "external_ref",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_headcounts",
                        to="schools.school",
                    ),
                ),
                (
                    "student_database_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="files.file",
                    ),
                ),
                (
                    "teams_info_photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="files.file",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("school", "grade", "section"),
                        name="unique_headcount_per_section",
                    )
                ],
            },
        ),
    ]
