# Generated by Django 5.2.17 on 2026-09-18 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0003_form2_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form1_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("complete", "Complete"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "form2_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("complete", "Complete"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("form3_pct", models.PositiveSmallIntegerField(default=0)),
                ("form4_pct", models.PositiveSmallIntegerField(default=0)),
                (
                    "kit_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("complete", "Complete"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("mismatch_flags", models.JSONField(blank=True, default=list)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
