# Generated by Django 5.2.17 on 2026-09-16 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("grade", models.PositiveSmallIntegerField()),
                ("section", models.CharField(max_length=5)),
                (
                    "unit",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Level 1"), (2, "Level 2"), (3, "Level 3")]
                    ),
                ),
                ("session_no", models.PositiveSmallIntegerField()),
                ("observed_by", models.CharField(blank=True, max_length=150)),
                ("date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_observations",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["school", "grade", "section", "unit", "session_no"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("school", "grade", "section", "unit", "session_no"),
                        name="unique_session_observation",
                    )
                ],
            },
        ),
    ]
